### ISSUE TITLE
ant run cannot start the application

### ISSUE THREAD

**Issue by zhouji2013** [floratos-lab/geworkbench#3]
When I do `ant run`, the application does not launch. The following error is displayed:
```
run:
     [java] -Xbootclasspath/p is no longer a supported option.
     [java] OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
     [java] Error: Could not create the Java Virtual Machine.
     [java] Error: A fatal exception has occurred. Program will exit.
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 0 seconds
```

**Comment by zhouji2013** [comment]
With this command `java -cp classes:lib/commons-digester.jar:lib/commons-logging.jar org.geworkbench.engine.config.UILauncher`, the splash screen can show up, with this output
```
zhouji@DESKTOP-VJR0I6H ~/git/geworkbench (master=) $ java -cp classes:lib/commons-digester.jar:lib/commons-logging.jar org.geworkbench.engine.config.UILauncher
*******************************************
geWorkbench invoked 2021-06-21 15:31:34.483
*******************************************
*******************************************
geWorkbench invoked 2021-06-21 15:31:34.483
*******************************************
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/collections/ArrayStack
        at org.apache.commons.digester.Digester.<init>(Digester.java:191)
        at org.geworkbench.engine.config.UILauncher.createDigester(UILauncher.java:81)
        at org.geworkbench.engine.config.UILauncher.main(UILauncher.java:222)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.ArrayStack
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more
```
Then I add one more jar `java -cp classes:lib/commons-digester.jar:lib/commons-logging.jar:lib/commons-collections.jar org.geworkbench.engine.config.UILauncher`, I see the further errors (totally expected because I did not add all jar files under lib)
```
*******************************************
geWorkbench invoked 2021-06-21 15:32:49.874
*******************************************
*******************************************
geWorkbench invoked 2021-06-21 15:32:49.874
*******************************************
Jun 21, 2021 3:32:50 PM org.apache.commons.digester.Digester endElement
SEVERE: End event threw error
java.lang.NoClassDefFoundError: org/apache/commons/beanutils/MethodUtils
        at org.apache.commons.digester.CallMethodRule.end(CallMethodRule.java:499)
        at org.apache.commons.digester.Rule.end(Rule.java:276)
        at org.apache.commons.digester.Digester.endElement(Digester.java:1064)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1377)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.apache.commons.digester.Digester.parse(Digester.java:1562)
        at org.geworkbench.engine.config.UILauncher.main(UILauncher.java:239)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.beanutils.MethodUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 16 more

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/beanutils/MethodUtils
        at org.apache.commons.digester.CallMethodRule.end(CallMethodRule.java:499)
        at org.apache.commons.digester.Rule.end(Rule.java:276)
        at org.apache.commons.digester.Digester.endElement(Digester.java:1064)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1377)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.apache.commons.digester.Digester.parse(Digester.java:1562)
        at org.geworkbench.engine.config.UILauncher.main(UILauncher.java:239)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.beanutils.MethodUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 16 more
```

**Comment by zhouji2013** [comment]
With this command `java -cp classes:lib/* org.geworkbench.engine.config.UILauncher`, the application is successfully launched, although it has the following error message on the console:
```
zhouji@DESKTOP-VJR0I6H ~/git/geworkbench (master=) $ java -cp classes:lib/* org.geworkbench.engine.config.UILauncher
*******************************************
geWorkbench invoked 2021-06-21 15:45:15.179
*******************************************
*******************************************
geWorkbench invoked 2021-06-21 15:45:15.179
*******************************************
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$2 (file:/home/zhouji/git/geworkbench/lib/cglib-nodep-2.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[geworkbench 2021-06-21 15:45:16,167] ERROR [main] org.apache.commons.digester.Digester.startElement(1270) | Begin event threw exception
java.lang.RuntimeException: Failed to instantiate plugin:class org.geworkbench.components.alignment.blast.BlastAnalysis
        at org.geworkbench.engine.config.PluginDescriptor.instantiate(PluginDescriptor.java:163)
        at org.geworkbench.engine.config.PluginDescriptor.<init>(PluginDescriptor.java:140)
        at org.geworkbench.engine.config.rules.PluginObject.createPlugin(PluginObject.java:159)
        at org.geworkbench.engine.config.rules.PluginRule.begin(PluginRule.java:65)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1268)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.apache.commons.digester.Digester.parse(Digester.java:1562)
        at org.geworkbench.engine.ccm.ComponentConfigurationManager.loadComponent(ComponentConfigurationManager.java:273)
        at org.geworkbench.engine.ccm.ComponentConfigurationManager.loadSelectedComponents(ComponentConfigurationManager.java:244)
        at org.geworkbench.engine.config.UILauncher.main(UILauncher.java:250)
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.Error-->Unresolved compilation problem:

        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:235)
        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:220)
        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:216)
        at net.sf.cglib.proxy.Enhancer.createUsingReflection(Enhancer.java:606)
        at net.sf.cglib.proxy.Enhancer.firstInstance(Enhancer.java:532)
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:220)
        at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:373)
        at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:281)
        at org.geworkbench.engine.management.ComponentRegistry$ComponentExtension.getExtension(ComponentRegistry.java:200)
        at org.geworkbench.engine.management.ComponentRegistry.createComponent(ComponentRegistry.java:419)
        at org.geworkbench.engine.config.PluginDescriptor.instantiate(PluginDescriptor.java:160)
        ... 18 more
Caused by: java.lang.Error: Unresolved compilation problem:

        at org.geworkbench.components.alignment.blast.AlgorithmMatcher.getInstance(AlgorithmMatcher.java:104)
        at org.geworkbench.components.alignment.blast.BlastAnalysisPanel.<clinit>(BlastAnalysisPanel.java:74)
        at org.geworkbench.components.alignment.blast.BlastAnalysis.<init>(BlastAnalysis.java:63)
        at org.geworkbench.components.alignment.blast.BlastAnalysis$$EnhancerByCGLIB$$fec97aab.<init>(<generated>)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:228)
        ... 28 more
org.xml.sax.SAXParseException; lineNumber: 32; columnNumber: 22; Error at (32, 22: Failed to instantiate plugin:class org.geworkbench.components.alignment.blast.BlastAnalysis
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2383)
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2409)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1271)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.apache.commons.digester.Digester.parse(Digester.java:1562)
        at org.geworkbench.engine.ccm.ComponentConfigurationManager.loadComponent(ComponentConfigurationManager.java:273)
        at org.geworkbench.engine.ccm.ComponentConfigurationManager.loadSelectedComponents(ComponentConfigurationManager.java:244)
        at org.geworkbench.engine.config.UILauncher.main(UILauncher.java:250)
Caused by: java.lang.RuntimeException: Failed to instantiate plugin:class org.geworkbench.components.alignment.blast.BlastAnalysis
        at org.geworkbench.engine.config.PluginDescriptor.instantiate(PluginDescriptor.java:163)
        at org.geworkbench.engine.config.PluginDescriptor.<init>(PluginDescriptor.java:140)
        at org.geworkbench.engine.config.rules.PluginObject.createPlugin(PluginObject.java:159)
        at org.geworkbench.engine.config.rules.PluginRule.begin(PluginRule.java:65)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1268)
        ... 14 more
Caused by: net.sf.cglib.core.CodeGenerationException: java.lang.Error-->Unresolved compilation problem:

        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:235)
        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:220)
        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:216)
        at net.sf.cglib.proxy.Enhancer.createUsingReflection(Enhancer.java:606)
        at net.sf.cglib.proxy.Enhancer.firstInstance(Enhancer.java:532)
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:220)
        at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:373)
        at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:281)
        at org.geworkbench.engine.management.ComponentRegistry$ComponentExtension.getExtension(ComponentRegistry.java:200)
        at org.geworkbench.engine.management.ComponentRegistry.createComponent(ComponentRegistry.java:419)
        at org.geworkbench.engine.config.PluginDescriptor.instantiate(PluginDescriptor.java:160)
        ... 18 more
Caused by: java.lang.Error: Unresolved compilation problem:

        at org.geworkbench.components.alignment.blast.AlgorithmMatcher.getInstance(AlgorithmMatcher.java:104)
        at org.geworkbench.components.alignment.blast.BlastAnalysisPanel.<clinit>(BlastAnalysisPanel.java:74)
        at org.geworkbench.components.alignment.blast.BlastAnalysis.<init>(BlastAnalysis.java:63)
        at org.geworkbench.components.alignment.blast.BlastAnalysis$$EnhancerByCGLIB$$fec97aab.<init>(<generated>)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at net.sf.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:228)
        ... 28 more
Mon Jun 21 15:45:16 EDT 2021
(C) 2012 Jmol Development
Jmol Version: 13.0.18  2013-06-16 18:53
java.vendor: Ubuntu
java.version: 11.0.11
os.name: Linux
Access: ALL
memory: 34.4/843.1
processors available: 20
useCommandThread: false
*******************************************
geWorkbench exited. 2021-06-21 15:45:35.346
*******************************************
*******************************************
geWorkbench exited. 2021-06-21 15:45:35.346
*******************************************
```

**Comment by zhouji2013** [comment]
The issue seems to be from net.sf.cglib.core.ReflectUtils

**Comment by zhouji2013** [comment]
There were two separate issues here:
1. `ant` or `ant run` cannot launch the app. This is `-Xbootclasspath/p` related. It has been fixed by the previous commit.
2. The exception related with "java.lang.Error: Unresolved compilation problem:". It is not clear why it happened, but when the app is completely re-complied, the problem disappeared. By 'completely re-compiled', I meant doing a `ant clean` before `ant run`, which of course will trigger bug #2, but that is a different issue. So I will close this bug.
